#!/bin/sh

usage() {
    cat <<EOF

usage: ${0##*/} [Distro]

  Options:

	--debian -d          Debian Based.
	--redhat -r             Red Hat Based.
	--arch -a             Arch Based.
	--suse -s             SUSE Based.
	--other -o             Other (Dont install dependences).

* Zget NillyTheL0L 2022-2022

EOF
}

[[ -z $1 ]] && {
    usage
    exit 1
}

debian(){
sudo echo Lets install dependences && sudo apt install libnotify-bin zenity wget -y &&  cd ~/ && wget https://raw.githubusercontent.com/NillyTheL0L/zget/main/zget && chmod +x zget && sudo mv zget /usr/bin && wget https://raw.githubusercontent.com/NillyTheL0L/zget/main/zget.desktop && sudo mv zget.desktop /usr/share/applications/ && wget https://github.com/NillyTheL0L/zget/raw/main/zget.png && sudo cp zget.png /usr/share/themes/Adwaita/gtk-2.0/assets/ && sudo mv zget.png /usr/share/themes/Adwaita-dark/gtk-2.0/assets/ && echo app installed with sucess type zget to open program
}
redhat(){
sudo echo Lets install dependences && sudo dnf install libnotify zenity wget && cd ~/ && wget https://raw.githubusercontent.com/NillyTheL0L/zget/main/zget && chmod +x zget && sudo mv zget /usr/bin && wget https://raw.githubusercontent.com/NillyTheL0L/zget/main/zget.desktop && sudo mv zget.desktop /usr/share/applications/ && wget https://github.com/NillyTheL0L/zget/raw/main/zget.png && sudo cp zget.png /usr/share/themes/Adwaita/gtk-2.0/assets/ && sudo mv zget.png /usr/share/themes/Adwaita-dark/gtk-2.0/assets/ && echo app installed with sucess type zget to open program
}
arch(){
sudo echo Lets install dependences && sudo pacman -S libnotify zenity wget --noconfirm && cd ~/ && wget https://raw.githubusercontent.com/NillyTheL0L/zget/main/zget && chmod +x zget && sudo mv zget /usr/bin && wget https://raw.githubusercontent.com/NillyTheL0L/zget/main/zget.desktop && sudo mv zget.desktop /usr/share/applications/ && wget https://github.com/NillyTheL0L/zget/raw/main/zget.png && sudo cp zget.png /usr/share/themes/Adwaita/gtk-2.0/assets/ && sudo mv zget.png /usr/share/themes/Adwaita-dark/gtk-2.0/assets/ && echo app installed with sucess type zget to open program
}
suse(){
sudo echo Lets install dependences && sudo zypper install libnotify zenity wget && cd ~/ && wget https://raw.githubusercontent.com/NillyTheL0L/zget/main/zget && chmod +x zget && sudo mv zget /usr/bin && wget https://raw.githubusercontent.com/NillyTheL0L/zget/main/zget.desktop && sudo mv zget.desktop /usr/share/applications/ && wget https://github.com/NillyTheL0L/zget/raw/main/zget.png && sudo cp zget.png /usr/share/themes/Adwaita/gtk-2.0/assets/ && sudo mv zget.png /usr/share/themes/Adwaita-dark/gtk-2.0/assets/ && echo app installed with sucess type zget to open program
}
other(){
sudo echo zget need libnotify, wget and zenity install it  && cd ~/ && wget https://raw.githubusercontent.com/NillyTheL0L/zget/main/zget && chmod +x zget && sudo mv zget /usr/bin && wget https://raw.githubusercontent.com/NillyTheL0L/zget/main/zget.desktop && sudo mv zget.desktop /usr/share/applications/ && wget https://github.com/NillyTheL0L/zget/raw/main/zget.png && sudo cp zget.png /usr/share/themes/Adwaita/gtk-2.0/assets/ && sudo mv zget.png /usr/share/themes/Adwaita-dark/gtk-2.0/assets/ && echo app installed with sucess type zget to open program
}



cat <<EOF
Zget
                                  NillyTheL0L - 2022-2022                
EOF

while [[ "$1" ]]; do
    read -s -n 1 -p "Do you want to continue?[y/N]: "
    [[ "$REPLY" == "y" ||  "$REPLY" == "Y" ]] && {
         echo
         case "$1" in
            --debian|-d) debian;;
            --redhat|-r) redhat;;
            --arch|-a) arch;;
            --suse|-s) suse;;
            --other|-o) other;;
        esac
        shift
    } || {
        printf "\nBye\n" "%s" && exit 0
    }

done
